language: bash

env:
  global:
    - GH_REF: github.com/sakyawang/sakyawang.github.com.git

script:
  - chmod +x gor
  - ./gor compile

after_script:
  - cd compiled
  - git init
  - git config user.name "sakyawang"
  - git config user.email "wanghao0319072@gmail.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}"  master:master
