language: bash

env:
  global:
    - GH_REF: sakyawang/sakyawang.github.com.git
    - secure: hVt5sfNx5AUutcmeOUanvOoJ2BHyHNigB0vkwG3FngB+wL6VcTpe3PL2BUyYXsuJGru4X/n8KuUGOAQe+boiye3AvVXNzknQPq/vZU0Jtqs5rBhaa+TVV8Z2RFYS3/7NjxbEEbosozzbwzwRPVfRqkOCMPU/oJmgY270Y0pk+DvTyfg7b2HLcLz2JVq1l/nVrp9MDYF6c+IiIy2/ouzLx+WqYlya54Ba3bbnlVELgagNqAtoeKPBDL4rH2JJofqUjOuwZjRZv5NJ9ztsC4cztptAqO5Ua2xQo0I9BO6ZyyqYZHwYvQ2E/tmnS5qiIMJqz+jpu6vyQLoFM48xLnSO+hK2TKj0SRN09HGKKy0pG0fe1PZZT8wqcpEtbi7sriUL5Fc/4XG6i9HEi0rtCXu/eXB0JxxZmgFG/+THBjKk6TJqr3fBxSeculH+7L0qkmqsN/TF0nabg95nclmLPgs+YD9oj2tzSMZl35Cg+0fdIpP5rL3dXX6jml7VXrb6L+MYjOjecUQA3oMDp8umdJwFT+UK2ixoKF/aVc5xHDhJPUZ1aOGoxzJM8CDaVpIpk+PypOx9D30fzuSKQkqhwuMfKrgPp/CRP8G0SjIz4w58oy03JzFYqboftpkr3T4Ux83e+767wQKUx2PFSPBtTorVjyN/AMkgxxRvyKlYkoreDOw= 

script:
  - chmod +x gor
  - ./gor compile

after_script:
  - cd compiled
  - git init
  - git config user.name "sakyawang"
  - git config user.email "wanghao0319072@gmail.com"
  - git add .
  - git commit -m "update blog"
  - git remote add origin https://${GH_TOKEN}@${GH_REF}
  - git push --force --quiet --set-upstream origin master
